version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - '27017:27017'

  redis_container:
    image: redis:latest
    ports:
      - '6379:6379'

  localstack_container:
    image: localstack/localstack:latest
    ports:
      - '4566-4599:4566-4599'
      - '8080:8080'
    environment:
      SERVICES: s3,sns,sts,sqs,apigateway,lambda,cloudformation,iam
      DEBUG: 1
      DATA_DIR: /tmp/localstack
      HOST_TMP_FOLDER: /tmp/localstack
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_REMOTE_DOCKER: 1
    volumes:
      - '/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$PWD/support/localstack:/docker-entrypoint-initaws.d' # create AWS resources on localstack

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
